modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
    modId="deafission" #mandatory
    version="1.20.1-0.13.0" #mandatory
    displayName="Dea's Fission"
    # A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    # A URL for the "homepage" for this mod, displayed in the mod UI
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    # A file name (in the root of the mod JAR) containing a logo for display
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors="Vazde"

    # The description text for the mod (multi line!) (#mandatory)
    description='''A fission reactor for GTCEu-m'''

# Forge
[[dependencies."deafission"]]
    modId="forge"
    mandatory=true
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies."deafission"]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

# Gregtech
[[dependencies."deafission"]]
    modId = "gtceu"
    mandatory = true
    versionRange = "7.2.0"
    ordering = "AFTER"
    side = "BOTH"

# ComputerCraft
[[dependencies."deafission"]]
    modId = "computercraft"
    mandatory = false
    versionRange = "[1.110,)"
    ordering = "AFTER"
    side = "SERVER"

#[[dependencies."deafission"]]
#    modId = "tfc"
#    mandatory = true
#    versionRange = "3.2.14"
#    ordering = "AFTER"
#    side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.deafission]
#openGLVersion="[3.2,)"